name: Healthcheck

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Pokedex health check
        uses: jtalk/url-health-check-action@f3f7bd79e4a64218eea7caad72796a1443896aeb
        with:
          url: https://pokedex-7irl.onrender.com/health
          max-attempts: 2
          retry-delay: 30s

      - name: Test Success
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: success()
        with:
          severity: info
          details: Healthcheck succeeded
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          details: Healthcheck failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
